spring.application.name=demo

# ===============================
# MySQL CONFIG
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# ===============================
# JPA Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.defer-datasource-initialization=true

# ===============================
# Multipart
# ===============================
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=500MB

# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

spring.h2.console.enabled=false
